"""upgrade-options-column

Revision ID: d145f4c9ed23
Revises: 9a3e0f8ec0d0
Create Date: 2024-03-11 22:45:48.581461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision = 'd145f4c9ed23'
down_revision = '9a3e0f8ec0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'options')
    op.add_column('questions', sa.Column('options', ARRAY(sa.String), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question_id', sa.INTEGER(), server_default=sa.text("nextval('questions_question_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_difficulty', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=800), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('question_id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.INTEGER(), server_default=sa.text("nextval('quizzes_quiz_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('quiz_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quiz_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('quiz_id', name='quizzes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('responses',
    sa.Column('response_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name='responses_question_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], name='responses_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='responses_user_id_fkey'),
    sa.PrimaryKeyConstraint('response_id', name='responses_pkey')
    )
    # ### end Alembic commands ###
